### ISSUE TITLE
Missing media in some retweet embeds

### ISSUE THREAD

**Issue by opon17** [HitomaruKonpaku/verniy-bot#36]
Hi! I noticed that retweet embeds sometimes do not include images and videos. This only seems to happen for the retweet link and not for the link to the original tweet, so I think a quick fix would be to hide the embed for the retweet instead of hiding it for the original tweet. Would such a change be ok?

**Comment by HitomaruKonpaku** [comment]
@opon17 ok i guess, but can i have some example on this case? 🤔

**Comment by opon17** [comment]
@HitomaruKonpaku Yes of course.

This is how the embeds look for some retweets:

- https://vxtwitter.com/nakiriayame/status/1753778691170316328
![image](https://github.com/HitomaruKonpaku/verniy-bot/assets/123262814/f498349c-6cf2-44e7-aab9-abe16a91c545)
- https://vxtwitter.com/nakiriayame/status/1757727069205893416
![image](https://github.com/HitomaruKonpaku/verniy-bot/assets/123262814/26c739e3-2d99-42f1-8a26-539781d82046)

And this would be how the embeds look for the original tweets:
- https://vxtwitter.com/hololivetv/status/1753750183165460818
![image](https://github.com/HitomaruKonpaku/verniy-bot/assets/123262814/4d149899-d1f6-4813-b238-2b20b0d6d2d6)
- https://vxtwitter.com/LaplusDarknesss/status/1757722567237157241
![image](https://github.com/HitomaruKonpaku/verniy-bot/assets/123262814/60f73da5-c2eb-4992-bd75-7703c6c32ee6)

I'm not sure why retweets embed like that, but it's not specific to vxtwitter. The same happens normal twitter links and fxtwitter. 🤔

**Comment by HitomaruKonpaku** [comment]
Updated & should be live now
