### ISSUE TITLE
not start

### ISSUE THREAD

**Issue by krswcat** [HitomaruKonpaku/verniy-bot#6]
Ubuntu 20.04
npm 8.11.0
node v16.15.1

> ubuntu@ip-***-**-*-***:~/verniy-bot$ npm start
> 
> > verniy-bot@1.8.4 start
> > node dist/index
> 
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module '/home/ubuntu/verniy-bot/dist/index'
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
>     at node:internal/main/run_main_module:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }

**Comment by HitomaruKonpaku** [comment]
Try to build first before run 🤔 

```
npm run build
```
